#!/bin/sh
# This script creates the model name symlink in /disk/usb.

set -e

# Replace spaces with underscores, remove special characters in vendor
# and model name.

mkdir -p /disk/usb

UM_VENDOR=`echo "$UM_VENDOR" | sed 's/ /_/g; s/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ._-]//g'`
UM_MODEL=`echo "$UM_MODEL" | sed 's/ /_/g; s/[^0123456789abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ._-]//g'`

# Exit if both vendor and model name are empty.
test -n "$UM_VENDOR" || test -n "$UM_MODEL" || exit 0

# Build symlink name.
if test -n "$UM_VENDOR" && test -n "$UM_MODEL"; then
    name="${UM_VENDOR}_$UM_MODEL"
else
    name="$UM_VENDOR$UM_MODEL"
fi

# Append partition number, if any, to the symlink name.
partition=`echo "$UM_DEVICE" | sed 's/^.*[^0123456789]\([0123456789]*\)/\1/'`
if test -n "$partition"; then
    name="${name}_$partition"
fi

# If the symlink does not yet exist, create it.
test -e "/disk/usb/$name" || ln -sf "$UM_MOUNTPOINT" "/disk/usb/$name"

exit 0
